var games = {
  'tloz': {
    'title': 'The Legend of Zelda',
    'category': 'Any% No Up+A',
    'offset': -1840,
    'splits': [
      'Dorite 2',
      'Dorite 1',
      'Dorite 3',
      'Dorite 4',
      'Dorite 5',
      'Dorite 7',
      'Dorite 6',
      'Dorite 8',
      'Princess',
    ],
  },
  'rollergames': {
    'title': 'Rollergames',
    'category': '',
    'offset': 0,
    'splits': [
      'Bad Attitude',
      'Mizz Georgia Hase',
      'Helicopter',
      'Maniacs',
      'John Guru Drew',
      'Truck',
      'Violators',
      'Chuck Skull',
      'Purple Maze',
      'Conveyor Belts',
      'Spike Ramps',
      'Diaper Genie',
    ],
  },
  'z2': {
    'title': 'Zelda II',
    'category': '100% All Keys',
    'offset': -2795,
    'splits': [
      'Shield|shield',
      'Candle|candle',
      'Palace 1|palace 1',
      'Jump|jump',
      'Life|life',
      'Hammer|hammer',
      'Medicine|medicine',
      'Fairy|fairy',
      'Glove|glove',
      'Palace 2|palace 2',
      'Wraaaaaaft|raft',
      'Palace 3|palace 3',
      'Fire|fire',
      'Kid|child',
      'Reflex|reflect',
      'Boots|boots',
      'Palace 4|palace 4',
      'Plunger|flute',
      'Palace 5|palace 5',
      'Spell|spell',
      'Cross|cross',
      'Palace 6|palace 6',
      'Thunder|thunder',
      'Triforce',
    ],
  },
  'trilogy': {
    'title': 'Zelda Rando Trilogy',
    'category': '',
    'offset': 0,
    'splits': [
      'The Legend',
      'The Adventure',
      'The Past',
    ],
  },
  'wacky': {
    'title': 'Wacky Races',
    'category': '',
    'offset': 0,
    'splits': [
      'Creepy Coupe',
      'Army Surplus Special',
      'Buzz Wagon',
      'Turbo Terrific',
      'Convert-a-Car',
      'Compact Pussycat',
      'Crimson Haybaler',
      'Bulletproof Bomb',
      'Arkansas Chugga-Bug',
      'Boulder-Mobile',
    ],
  },
  'panic': {
    'title': 'Panic Restaurant',
    'category': '',
    'offset': -1100,
    'splits': [
      'Appetizer',
      'Soup',
      'Salad',
      'Fish',
      'Meat',
      'Dessert',
    ],
  },
  'digger': {
    'title': 'Lil Digger',
    'category': '',
    'offset': 0,
    'splits': [
      'Level 1',
      'Fin',
    ],
  },
  'lotw': {
    'title': 'Legacy of the Wizard',
    'category': 'blind%',
    'offset': 0,
    'splits': [
      'Find a new room',
      'Fall asleep in chair',
      'Go to bed',
    ],
  },
  'ypm': {
    'title': 'Yume Penguin Monogatari',
    'category': '',
    'offset': -2500,
    'splits': [
      'Swipe Left',
      'Pig Blimp',
      'Frosting',
      'Bird Thing',
      'Pirate Penguin',
      'Swipe Right',
    ],
  },
  'band': {
    'title': 'Putting the Band Back Together',
    'category': '',
    'offset': 0,
    'splits': [
      'Recorder',
      'Harp',
      'Ocarina',
      'Chime',
      'Horn',
    ],
  },
  'multi': {
    'title': 'Set up a multi game race',
    'category': '',
    'offset': 0,
    'splits': [
      'Discuss games',
      'Discuss goals',
      'Discuss games again because someone joined',
      'Discuss order of games',
      'Discuss flags',
      'Set goal',
      'Set new seed because one randomizer crashed',
      '.ready',
    ],
  },
  'crown': {
    'title': 'Flutes and Crowns',
    'category': '',
    'offset': 0,
    'splits': [
      'Z1 Flute',
      'Buffer',
      'Z2 Flute',
      'Buffer',
      'DW Flute',
      'Buffer',
      'FF Crown',
      'Buffer',
      'LotW 2 Crowns',
    ],
  },
};
