var games = {
  'tloz': {
    'title': 'The Legend of Zelda',
    'category': 'Any% No Up+A',
    'offset': -1840,
    'splits': [
      'Dorite 2',
      'Dorite 1',
      'Dorite 3',
      'Dorite 4',
      'Dorite 5',
      'Dorite 7',
      'Dorite 6',
      'Dorite 8',
      'Princess',
    ],
  },
  'rollergames': {
    'title': 'Rollergames',
    'category': '',
    'offset': 0,
    'splits': [
      'Bad Attitude',
      'Mizz Georgia Hase',
      'Helicopter',
      'Maniacs',
      'John Guru Drew',
      'Truck',
      'Violators',
      'Chuck Skull',
      'Purple Maze',
      'Conveyor Belts',
      'Spike Ramps',
      'Diaper Genie',
    ],
  },
  'z2': {
    'title': 'Zelda II',
    'category': '100% All Keys',
    'offset': -2795,
    'splits': [
      'Palace 1',
      'Jump',
      'Life',
      'Hammer',
      'Fairy',
      'Palace 2',
      'Palace 3',
      'Fire',
      'Reflect',
      'Palace 4',
      'Palace 5',
      'Spell',
      'Palace 6',
      'Enter GP',
      'Triforce',
    ],
  },
  'trilogy': {
    'title': 'Zelda Rando Trilogy',
    'category': '',
    'offset': 0,
    'splits': [
      'The Legend',
      'The Adventure',
      'The Past',
    ],
  },
  'wacky': {
    'title': 'Wacky Races',
    'category': '',
    'offset': 0,
    'splits': [
      'Hip Hop 1',
      'Hip Hop 2',
      'Hip Hop 3',
      'Splish Splash 1',
      'Splish Splash 2',
      'Splish Splash 3',
      'Go Go America 1',
      'Go Go America 2',
      'Go Go America 3',
      'Go Go America 4',
    ],
  },
};
